# Generated by Django 2.1.7 on 2019-04-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('regularExpression', models.TextField(db_column='regular_expression')),
                ('fileType', models.CharField(db_column='file_type', max_length=5)),
                ('initialCode', models.TextField(db_column='initial_code')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'FileTypes',
            },
        ),
    ]
