# Generated by Django 2.1.7 on 2019-04-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='initialCode',
            field=models.TextField(blank=True, db_column='initial_code', null=True),
        ),
    ]
